### ISSUE TITLE
Listener 会被回调两次（onRefresh() 或 onLoadMore()）

### ISSUE THREAD

**Issue by 327968168** [liaoinstan/SpringView#1]
在使用RecyclerView时（版本 23.4.0），下拉刷新或者上拉加载 Listener 都会被回调两次

**Comment by fishwjy** [comment]
同上，我的RecyclerView版本是recyclerview-v7-23.3.0，也出现了两次回调

**Comment by fishwjy** [comment]
粗略看了一下代码，是否将computeScroll()函数改成这样：
`@Override
    public void computeScroll() {
        if (mScroller.computeScrollOffset()) {
            scrollTo(0, mScroller.getCurrY());
            invalidate();
            return;
        }
        //在滚动动画完全结束后回调接口
        if (!isMoveNow && type==Type.FOLLOW && mScroller.isFinished()){
            if (isFullAnim) {
                callOnAfterFullAnim();
            } else {
                 callOnAfterRefreshAnim();
            }
        }
    }`
就是滚动没结束的时候不去执行回调，等结束之后再回调，即在invalidate()之后加上return;

目前只在RecyclerView当中测试了一下，现在只回调一次了，但不知这样是否影响其他逻辑，请作者定夺

**Comment by 327968168** [comment]
@fishwjy  Type.OVERLAP只回调一次，Type.FOLLOW 会回调两次

**Comment by fishwjy** [comment]
哦，我是在Type.FOLLOW 的情况下测试的，没有换到Type.OVERLAP下

**Comment by liaoinstan** [comment]
感谢你的建议，已经修复了，代码已经更新

**Comment by yuzhongxingke** [comment]
好像还没有修复，在 Demo1中也有这种问题，比如我下拉刷新时，下拉刷新中时，我再下拉一次时，会执行两次刷新监听，而且正在刷新时下拉刷新的文字也会改变(应该不变动的）
