### ISSUE TITLE
华为 PIC TL00出现java.lang.IllegalStateException

### ISSUE THREAD

**Issue by zhouchaohao** [liaoinstan/SpringView#76]
java.lang.IllegalStateException
The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131755735, class android.widget.ListView) with Adapter(class michat.sweet.main.framents.message.VideoRecordFragment$VideoRecordAdapter)]

widgets.springview.SpringView.doMove(SpringView.java:378)

1 android.widget.ListView.layoutChildren(ListView.java:1623)
2 android.widget.AbsListView.onLayout(AbsListView.java:2212)
3 android.view.View.layout(View.java:17694)
4 android.view.ViewGroup.layout(ViewGroup.java:5631)
5 michat.sweet.main.widgets.springview.SpringView.doMove(SpringView.java:378)
6 michat.sweet.main.widgets.springview.SpringView.onTouchEvent(SpringView.java:260)
7 android.view.View.dispatchTouchEvent(View.java:10013)
8 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
9 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
10 michat.sweet.main.widgets.springview.SpringView.dispatchTouchEvent(SpringView.java:236)
11 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
12 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
13 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
14 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)

在华为手机上会出现这个问题，大佬们帮帮忙

**Comment by liaoinstan** [comment]
这个报错跟SpringView没有关系，你在子线程修改了listView的数据源
