### ISSUE TITLE
加载更多时的两个问题

### ISSUE THREAD

**Issue by yongshengdev** [liaoinstan/SpringView#78]
作者你好，项目中用的你的SpringView，加载更多时，发现了两个问题：1.加载更多完毕后，最新的数据没有显示出来，我在onFinishFreshAndLoad向下滚动了一段距离但体验很差2.加载更多时，应该加一个isLoading的判断，再次上拉加载的时候判断isLoading不会回调onLoadMore，onFinishFreshAndLoad时isLoading为false，不然数据会重复。

**Comment by liaoinstan** [comment]
收到你的merge了，下一次发布会修复这个问题
