### ISSUE TITLE
下拉刷新和上拉加载一直转不消失

### ISSUE THREAD

**Issue by DuZhengLin17** [liaoinstan/SpringView#85]
作者大大你好，我使用这个的时候 设置的默认的头部和尾部 为什么  就是不消失呢 一直转圈圈，用了onFinishFreshAndLoad也没用

**Comment by liaoinstan** [comment]
?  试试onFinishFreshAndLoadDelay

**Comment by liaoinstan** [comment]
?  试试onFinishFreshAndLoadDelay
