### ISSUE TITLE
功能咨询

### ISSUE THREAD

**Issue by qiushui95** [liaoinstan/SpringView#97]
首先，感谢作者开源。
刷新和加载更多的时候是否支持只显示动画，不触发listener。不是用户下拉的操作，是代码调用的刷新显示动画

**Comment by liaoinstan** [comment]
不支持，不管是手拉还是自动，刷新过程一定会回调listener，如果你不希望有回调，你可以在你的listener回调里进行判断跳过你的业务逻辑就好了

**Comment by qiushui95** [comment]
@qiushui95 好的  谢谢。我的是响应式布局，刷新状态在ViewModel中，刷新开始操作在ViewModel中进行，页面只展示动画。，除非是用户手动下拉操作。
